version: '3.8'
services:
  main:
    build: ./main
    image: main-image
    container_name: main-container
    depends_on:
      file-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - FILE_URL_DB=jdbc:postgresql://file-db:5432/file
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

  file-db:
    image: postgres:14-alpine
    container_name: file-db
    ports:
      - "5466:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=file
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data:
